apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-token-renewer
spec:
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: github-token-renewer
          volumes:
            - name: config
              configMap:
                name: github-token-renewer-config
            - name: github-app-private-key
              secret:
                secretName: github-app-private-key
          containers:
            - name: renewer
              image: ghcr.io/takutakahashi/github-token-renewer:v0.3.0
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
                limits:
                  cpu: 100m
                  memory: 500Mi
              command:
                - /github-token-renewer
                - -c
                - /etc/github-token-renewer/config.yaml
              volumeMounts:
                - name: config
                  mountPath: /etc/github-token-renewer
                - name: github-app-private-key
                  mountPath: /token
          restartPolicy: OnFailure
