kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-token-renewer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - create
  - patch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-token-renewer
subjects:
- kind: ServiceAccount
  name: github-token-renewer
roleRef:
  kind: ClusterRole
  name: github-token-renewer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-token-renewer
